### ISSUE TITLE
Code formatting

### ISSUE THREAD

**Issue by nopeslide** [alrevuelta/cONNXr#12]
Since we are adding a lot of autogenerated code and formatting this code is pure pain.
How about we add some kind of code formatter for the whole project?

- `clang-format`
  - simple config
    - common styles
    - hate it or love it approach
  - intended for c++
- `uncrustify`
  - complex config
    - almost every token transition is configurable
    - pain to configure

currently I'm evaluating both for another project and am leaning towards `uncrustify`

**Comment by alrevuelta** [comment]
Great idea. I haven't used neither of them but found that `clang-format` has a GitHub Action CI built on top that can act as a linter. So I guess the idea here would be to use the code formatter locally, and then on CI enforce that all the code is formatted accordingly (but without auto formatting it).

The action [is this one](https://github.com/marketplace/actions/clang-format-lint) (not widely used though). Since its built on top `clang-format`, we can share the configuration file for both the formatter and CI linter.

Nothing against `uncrustify` but couldn't find the linter functionality for it.

**Comment by nopeslide** [comment]
> Great idea. I haven't used neither of them but found that `clang-format` has a GitHub Action CI built on top that can act as a linter. So I guess the idea here would be to use the code formatter locally, and then on CI enforce that all the code is formatted accordingly (but without auto formatting it).
> 

that's exactly how it's done 

> The action [is this one](https://github.com/marketplace/actions/clang-format-lint) (not widely used though). Since its built on top `clang-format`, we can share the configuration file for both the formatter and CI linter.
> 
> Nothing against `uncrustify` but couldn't find the linter functionality for it.

what do you mean by linting support (except an ide integration)?
A check if code conforms is usually done by formatting it and checking if git reports any differences (`git diff --exit-code`)

**Comment by alrevuelta** [comment]
> what do you mean by linting support (except an ide integration)?
A CI check if code conforms can be simply done by formatting it and checking if git reports any differences (git diff --exit-code).
Git can also be used to generate diffs explaining the differences

I guess the mentioned action is doing something like that under the hood, format the code and diff to check if the code conforms. Maybe even show the mismatches in some fancy way. Here is an example: https://github.com/tensorflow/addons/runs/422021572?check_suite_focus=true

**Comment by nopeslide** [comment]
> Maybe even show the mismatches in some fancy way.
>

does it get more fancy than this?
```bash
git ls-files -ico -x '**/*.c' -x '**/*.h' | xargs -I % sh -c "clang-format % | git diff --exit-code --no-index --color --word-diff-regex=. % -"
```
![image](https://user-images.githubusercontent.com/42803409/80281036-a5d66200-8708-11ea-950e-7907675868ca.png)
