### ISSUE TITLE
Related projects

### ISSUE THREAD

**Issue by robinvanemden** [alrevuelta/cONNXr#23]
I just ran cONNXr's MNIST and Yolo examples, and both work like a charm 😄 

As I recently ran into two related projects, I thought I'd mention those here as well:

- https://github.com/ai-techsystems/deepC
- https://github.com/ONNC/onnc 

The latter implements quite a few operators in C: https://github.com/ONNC/onnc/tree/master/lib/Runtime/operator

Possibly of interest for cONNXr too?

**Comment by alrevuelta** [comment]
Definitely those projects are interesting for us, specifically `onnc`.

Thanks for sharing!
