### ISSUE TITLE
Mitigation of windows missing weak symbol support 

### ISSUE THREAD

**Issue by nopeslide** [alrevuelta/cONNXr#35]
I see these options regarding windows:
1. "drop" support
   - wsl is capable of executing linux binaries
   - cygwin injects its own dll that wraps syscalls
   - wsl is much better at doing this than cygwin will ever be
2. try mingw-w64
   - the old mingw also had problems with weak attributes
3. try other win c compilers
   - most of them are proprietary 
4. replace weak attributes with preprocessor magic
   - maybe even Kconfig or sth similar?
   - not a big fan of this one, because we would move a lot of complexity inside the build system
currently we can just omit sth while compiling and it's still a valid build (because stubs just take over)
with Kconfig we have a config dictating the build process and if we forget to integrate it somewhere we get into trouble.

_Originally posted by @nopeslide in https://github.com/alrevuelta/cONNXr/pull/34#issuecomment-653758748_

**Comment by alrevuelta** [comment]
The whole point of this project is to have a runtime that is as simple as possible and that can be compiled in with every compiler. If we start to rely on compiler-dependant features that are not widely supported by all compilers, we are losing the purpose of the project.

My suggestion is the following. We can get rid of all `extern`, `weak` and so on, and just have normal function prototypes.

```c
//operator__onnx__conv__11.h file

operator_status operator__onnx__conv__11__T_tensor_float(
    node_context *ctx
);
operator_status operator__onnx__conv__11__T_tensor_float16(
    node_context *ctx
);
```

Then we autogenerate all files + functions with some dummy implementation.

```c
//operator__onnx__conv__11__T_tensor_float.c file
operator__onnx__conv__11__T_tensor_float(node_context *ctx)
{
  return NOT_IMPLEMENTED;
}
```

```c
//operator__onnx__conv__11__T_tensor_float16
operator__onnx__conv__11__T_tensor_float16(node_context *ctx)
{
  return NOT_IMPLEMENTED;
}
```

And then if someone wants to implement an operator, they just have to locate the function/file (`operator__onnx__conv__11__T_tensor_float` for example) remove the `return NOT_IMPLEMENTED` and implement the operator.


Maybe not as fancy as using weak attributes, but do we really need that? This would fix also #32. Why not abstracting other developers form the complexity of generating all this? Just leave a function in place ready to be implemented.
