### ISSUE TITLE
directory structure for operators

### ISSUE THREAD

**Issue by nopeslide** [alrevuelta/cONNXr#41]
In the future we can create one folder per operator so it looks less messy, but lets leave it for another patch.

_Originally posted by @alrevuelta in https://github.com/alrevuelta/cONNXr/pull/34#issuecomment-657605954_

**Comment by nopeslide** [comment]
what do you think about restructuring all operator files in such a manner?
`/src/operator/<domain>/<name>/<version>/`
und putting all files like `info_`, `resolve_` etc in there?
one dir for all operator related files.

**Comment by alrevuelta** [comment]
@nopeslide Looks good. Something like this I guess.

So operator `Conv` would have:
* src/operator/onnx/operator_onnx_conv/
  * src/operator/onnx/operator_onnx_conv/version_11
    * Implementation 1: operator__onnx__conv__11__T_tensor_double.c
    * Implementation 2: operator__onnx__conv__11__T_tensor_float.c
    * Implementation 3: operator__onnx__conv__11__T_tensor_float16.c
    * Info: info_operator__onnx__conv__11.c
    * Resolver: resolve_operator__onnx__conv__11.c
  * src/operator/onnx/operator_onnx_conv/version_xx
    * ...

**Comment by nopeslide** [comment]
@alrevuelta 
would simplify it a bit more to sth like this
`src/operator/onnx/conv/11/operator__onnx__conv__11__T_tensor_double.c`

**Comment by alrevuelta** [comment]
> would simplify it a bit more to sth like this
src/operator/onnx/conv/11/operator__onnx__conv__11__T_tensor_double.c

sure
