### ISSUE TITLE
Build connxr as a shared library, to enable python bindings for testing 

### ISSUE THREAD

**Issue by nopeslide** [alrevuelta/cONNXr#60]
- Python should be our way to test things
- Having python bindings would simplify testing a lot
  - can use the onnx python library, numpy, onnxruntime etc
  - no need to generate files, everything can be done in memory
- Central script that does all the testing
  - can generate the operator status overview (#44) and more

**Comment by alrevuelta** [comment]
You mean stop using CUnit and move to a Python based framework? Thumbs up for that.

**Comment by nopeslide** [comment]
> You mean stop using CUnit and move to a Python based framework? Thumbs up for that.

exactly :)
