### ISSUE TITLE
cannot find -lcunit

### ISSUE THREAD

**Issue by dujtep-airtech** [alrevuelta/cONNXr#84]
I'm download and try to build file with "make all" command. I got this error

gcc -shared -o build/libconnxr.so -fpic -I include  -I src  -I src/pb  -std=c99 -Wall -g3 -gdwarf -O2 -fpic -g -lcunit -lm `find build/src/ -type f`
/usr/bin/ld: cannot find -lcunit
collect2: error: ld returned 1 exit status
make: *** [Makefile:105: build/sharedlib] Error 1

**Comment by nopeslide** [comment]
you need to install cunit. it is not included in this project.

**Comment by nopeslide** [comment]
@dujtep-airtech if this is still an issue, please reopen it
