### ISSUE TITLE
build fail on linux and mac

### ISSUE THREAD

**Issue by iamfaith** [alrevuelta/cONNXr#87]
gcc -o build/src/trace.o -c -std=c99 -Wall -g3 -gdwarf -O2 -fpic -I/home/linuxbrew/.linuxbrew/opt/isl@0.18/include -I include  -I src  -I src/pb  src/trace.c
gcc -o build/src/utils.o -c -std=c99 -Wall -g3 -gdwarf -O2 -fpic -I/home/linuxbrew/.linuxbrew/opt/isl@0.18/include -I include  -I src  -I src/pb  src/utils.c
gcc -o build/src/test/test_utils.o -c -std=c99 -Wall -g3 -gdwarf -O2 -fpic -I/home/linuxbrew/.linuxbrew/opt/isl@0.18/include -I include  -I src  -I src/pb  src/test/test_utils.c
gcc -shared -o build/libconnxr.so -fpic -I/home/linuxbrew/.linuxbrew/opt/isl@0.18/include -I include  -I src  -I src/pb  -std=c99 -Wall -g3 -gdwarf -O2 -fpic -L/home/linuxbrew/.linuxbrew/opt/isl@0.18/lib -g -lcunit -lm `find build/src/ -type f`
/usr/bin/ld: cannot find -lcunit
collect2: error: ld returned 1 exit status
Makefile:105: recipe for target 'build/sharedlib' failed
make: *** [build/sharedlib] Error 1

uname -a

Linux faith 5.4.0-53-generic #59~18.04.1-Ubuntu SMP Wed Oct 21 12:14:56 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.5 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

**Comment by alrevuelta** [comment]
Thanks for reporting the issue. Which commit are you running and which command? `make all`? Works fine for me on mac and linux CI (which is also Ubuntu) is also fine.

**Comment by nopeslide** [comment]
> /usr/bin/ld: cannot find -lcunit
> collect2: error: ld returned 1 exit status

Install `cunit` via your package manager and you should be fine.
`cunit` is the only dependency we have for..well..testing

**Comment by nopeslide** [comment]
@alrevuelta since this is the second issue regarding missing `cunit` installation, should we add information about this to the README?

**Comment by iamfaith** [comment]
Thanks. I found this command to solve this issue.

```
sudo apt-get install libcunit1 libcunit1-doc libcunit1-dev
```

**Comment by nopeslide** [comment]
> `sudo apt-get install libcunit1 libcunit1-doc libcunit1-dev`

thanks. will add this to the README
